version: "3.8"

services:
  postgresql:
    container_name: api-todo
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
